# Generated by Django 5.0 on 2023-12-06 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
                ('fathers_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='отчество')),
                ('surname', models.CharField(max_length=150, verbose_name='фамилия')),
                ('email', models.CharField(max_length=150, verbose_name='email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('surname',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'сообщение для рассылки',
                'verbose_name_plural': 'сообщения для рассылки',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(auto_now=True, verbose_name='Дата и время последней попытки')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='статус попытки')),
                ('response', models.IntegerField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.message', verbose_name='Сообщение для рассылки')),
            ],
            options={
                'verbose_name': 'лог рассылки',
                'verbose_name_plural': 'логи рассылки',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.DateField(auto_now=True, verbose_name='время рассылки')),
                ('periodicity', models.CharField(choices=[('once_a_day', 'Once a Day'), ('once_a_week', 'Once a Week'), ('once_a_month', 'Once a Month')], default='once_a_day', max_length=20, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('created', 'Created'), ('started', 'Started')], default='created', max_length=20, verbose_name='статус рассылки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'настройки',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.settings', verbose_name='Настройки рассылки'),
        ),
    ]
