# Generated by Django 5.0 on 2023-12-06 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client',
            field=models.ForeignKey(default='неизвестный', on_delete=django.db.models.deletion.CASCADE, to='mailings.client', verbose_name='Клиент'),
        ),
    ]
