# Generated by Django 5.0 on 2023-12-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='response',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(default='completed', max_length=50, verbose_name='статус попытки'),
        ),
    ]
