# Generated by Django 5.0 on 2023-12-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_logs_response_alter_logs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='last_attempt',
            field=models.CharField(max_length=25, verbose_name='Дата и время последней попытки'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(default='completed ', max_length=50, verbose_name='статус попытки'),
        ),
    ]
