# Generated by Django 5.0 on 2023-12-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_logs_last_attempt_alter_logs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(default='completed', max_length=50, verbose_name='статус попытки'),
        ),
    ]
