# Generated by Django 5.0 on 2023-12-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_alter_logs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='last_attempt',
            field=models.CharField(max_length=200, verbose_name='Дата и время последней попытки'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='response',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(default='completed', max_length=200, verbose_name='статус попытки'),
        ),
    ]
