# Generated by Django 5.0 on 2023-12-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_alter_logs_last_attempt_alter_logs_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='last_attempt',
            field=models.DateTimeField(verbose_name='Дата и время последней попытки'),
        ),
    ]
