# Generated by Django 5.0 on 2024-01-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_alter_logs_last_attempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержимое статьи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mailings/images/', verbose_name='изображение')),
                ('number_of_views', models.PositiveIntegerField(default=0, verbose_name='количество просмотров')),
                ('date_of_publication', models.DateField(verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
